[general]
live_config_reload = true

[window]
opacity = 0.8

[font]
normal = { family = "JetBrains Mono", style = "Regular" }

[keyboard]
bindings = [
	{ key = "x", mods = "Control", action = "ToggleViMode" },
]
